#include "font/lv_font.h"
#include "lvgl.h"
#include "ui.h"
extern const lv_font_t ui_font_Hollow85;

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project



void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_power = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_power, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_power, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_power, -1);
  // moved down a bit for RPM gauge
  lv_obj_set_y(ui_power, 100);
  lv_obj_set_align(ui_power, LV_ALIGN_CENTER);
  lv_label_set_text(ui_power, "76");
  lv_obj_set_style_text_color(ui_power, lv_color_hex(0xD8D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_power, &ui_font_Hollow85,LV_PART_MAIN | LV_STATE_DEFAULT);
                             

  ui_Arc1 = lv_arc_create(ui_Screen1);
  lv_obj_set_width(ui_Arc1, 186);
  lv_obj_set_height(ui_Arc1, 186);
  lv_obj_set_x(ui_Arc1, -71);
  lv_obj_set_y(ui_Arc1, 0);
  lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE);  /// Flags
  lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  /* MAIN arc (background) thickness */
  lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

  /* INDICATOR arc thickness + color */
  lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x20662E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  /* Knob (hidden) */
  lv_obj_set_style_radius(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0x858585), LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

  /* Bring arc to front */
  lv_obj_move_foreground(ui_Arc1);





  ui_Arc2 = lv_arc_create(ui_Screen1);
  lv_obj_set_width(ui_Arc2, 130);
  lv_obj_set_height(ui_Arc2, 130);
  lv_obj_set_x(ui_Arc2, 109);
  lv_obj_set_y(ui_Arc2, 0);
  lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Arc2, LV_OBJ_FLAG_CLICKABLE);  /// Flags
  lv_obj_set_style_arc_width(ui_Arc2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x858585), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_width(ui_Arc2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_radius(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x858585), LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);




  ui_Arc3 = lv_arc_create(ui_Screen1);  //no
  lv_obj_set_width(ui_Arc3, 110);
  lv_obj_set_height(ui_Arc3, 110);
  lv_obj_set_x(ui_Arc3, 143);
  lv_obj_set_y(ui_Arc3, -107);
  lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Arc3, LV_OBJ_FLAG_CLICKABLE);  /// Flags
  lv_obj_set_style_arc_width(ui_Arc3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x858585), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_width(ui_Arc3, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_radius(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0x858585), LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

  ui_Arc4 = lv_arc_create(ui_Screen1);  //no use
  lv_obj_set_width(ui_Arc4, 110);
  lv_obj_set_height(ui_Arc4, 110);
  lv_obj_set_x(ui_Arc4, 143);
  lv_obj_set_y(ui_Arc4, 107);
  lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Arc4, LV_OBJ_FLAG_CLICKABLE);  /// Flags
  lv_obj_set_style_arc_width(ui_Arc4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0x858585), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_width(ui_Arc4, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_radius(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0x858585), LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

  ui_power1 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_power1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_power1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_power1, 109);
  lv_obj_set_y(ui_power1, 44);
  lv_obj_set_align(ui_power1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_power1, "34");
  lv_obj_set_style_text_color(ui_power1, lv_color_hex(0xD8D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_power1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_power1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_power2 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_power2, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_power2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_power2, 43);
  lv_obj_set_y(ui_power2, 342);
  lv_obj_set_align(ui_power2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_power2, "27");
  lv_obj_set_style_text_color(ui_power2, lv_color_hex(0xD8D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_power2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_power2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_power3 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_power3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_power3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_power3, 43);
  lv_obj_set_y(ui_power3, -94);
  lv_obj_set_align(ui_power3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_power3, "72");
  lv_obj_set_style_text_color(ui_power3, lv_color_hex(0xD8D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_power3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_power3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);


  // Text under RPM gauge
  ui_Label2 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label2, 80);
  lv_obj_set_y(ui_Label2, -48);
  lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label2, "volt");
  lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label2, &ui_font_Hollow85,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  // Text under RPM gauge
  ui_Label3 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label3, 80);
  lv_obj_set_y(ui_Label3, 10);
  lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label3, "12,5");
  lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x234D12), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label3, &ui_font_Hollow85,
                             LV_PART_MAIN | LV_STATE_DEFAULT);



  ui_colorPNL = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_colorPNL, 54);
  lv_obj_set_height(ui_colorPNL, 24);
  lv_obj_set_x(ui_colorPNL, 126);
  lv_obj_set_y(ui_colorPNL, -92);
  lv_obj_set_align(ui_colorPNL, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_colorPNL, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_colorPNL, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_colorPNL, lv_color_hex(0x858585), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_colorPNL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_colorPNL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel8 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel8, 480);
  lv_obj_set_height(ui_Panel8, 65);
  lv_obj_set_x(ui_Panel8, -99);
  lv_obj_set_y(ui_Panel8, -142);
  lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Panel8, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x858585), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel9 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel9, 200);
  lv_obj_set_height(ui_Panel9, 155);
  lv_obj_set_x(ui_Panel9, -99);
  lv_obj_set_y(ui_Panel9, 220);
  lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Panel9, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x6E6969), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel10 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel10, 200);
  lv_obj_set_height(ui_Panel9, 155);
  lv_obj_set_x(ui_Panel10, 9);
  lv_obj_set_y(ui_Panel10, 220);
  lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Panel10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x6E6969), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


  ui_Label5 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label5, 45);
  lv_obj_set_y(ui_Label5, -135);
  lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label5, "Janine");
  lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label6 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label6, -53);
  lv_obj_set_y(ui_Label6, -142);
  lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label6, "RWB");
  lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
 lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
   // lv_obj_set_style_text_font(ui_Label6, &ui_font_Hollow85,LV_PART_MAIN | LV_STATE_DEFAULT);
}
